.gitignore
backend/__init__.py
backend/app.py
backend/cv/__init__.py
backend/cv/ocr.py
backend/io/__init__.py
backend/io/image_loader.py
backend/llm/__init__.py
backend/llm/language_model.py
backend/utils/__init__.py
backend/utils/image.py
requirements.txt
tests/test_app.py

This pull request sets up the base structure for FertiScan. It includes the initial project organization, the creation of necessary directories and files, and the implementation of basic class definitions.
- Add unit tests.
- Implement the detailed logic for each module.
- Document each module and its usage in the README.

Project Structure and Base Setup

---

.env.template
README.md
app.py
requirements.txt

added a field to .env.template
added flask-cors to dependencies
used flask_cors to authorize connection from FRONTEND_URL

Fixes #21 : Need to fix CORS to link backend and frontend

---

.gitignore
backend/document_storage.py
tests/test_document_storage.py

Linked to https://github.com/ai-cfia/fertiscan-backend/issues/24

Change DocumentStorage to work with the test

---

prompt.txt

just so backend and frontend have the same value when communicate

removing maj

---

app.py
backend/ocr.py
requirements.txt
tests/test_ocr.py

Use the latest preview document intelligence API for mardown support.
Closes #40

Issue #40: Improve OCR

---

.github/workflows/fertiscan-backend-workflows.yaml
Dockerfile

Testing the coverage of fertiscan-backend
- Closes #24

issue #24: coverage tests

---

.coveragerc
tests/test_auth.py
tests/test_label.py

Improve the test coverage

---

app.py
backend/form.py
tests/test_form.py

Issue #83: Support NPK with floats

---

Dockerfile

issue #98: fixed dockerfile

---

app.py

Remove the `/` endpoint which didn't work in the first place.

Remove the `/` endpoint

---

README.md
docs/README.md

Issue #97: Developer documentation

---

.github/workflows/fertiscan-backend-workflows.yaml
.github/workflows/fertiscan-create-release.yaml
README.md
docs/plantuml/analyze_dss.puml

feat pr labelling workflow

---

app.py

Issue #93: update default value for UPLOAD_FOLDER in app.py

---

Dockerfile
README.md
app.py

Ref: https://github.com/ai-cfia/fertiscan-backend/issues/128

Issue #128: update Dockerfile with missing dependencies and env variables

---

app.py
connection_manager.py
requirements.txt
tests/test_app.py
tests/test_connection_manager.py

issue #131: pool connection manager

---

.env.template
app.py
backend/connection_manager.py
tests/test_app.py

The application logs are returned in the terminal console.

Logs returned in the console

---

app.py

Add a new route to the Flask application that redirects the root URL to the "apidocs/" endpoint. This will provide a more user-friendly experience when accessing the application.
The redirect is implemented using the `redirect` function from the Flask library, and the HTTP status code `HTTPStatus.OK` is returned to indicate a successful redirection.
This commit addresses the need to improve the user experience by providing a clear entry point to the application.
Refs: #N/A

Add redirect to main page

---

.env.template
.gitignore
Dockerfile
app.py
docker-compose.yml
requirements.txt

Fix #136 
What has been done :
- added a new env value API_BASE_PATH
- added swagger_config to be able to modify the config ( it is not modifiable once flasgger has been created )
- modify the config to change the url_prefix by the env value (changes the url for swagger ui)
- modify the template to change the basePath by the env value (changes the url for the api routes)

Fix : As a dev, I want to fix the swagger on the deployment #136

---

requirements.txt

This PR is to build an image with the latest datastore changes.

Latest datastore changes

---

tests/test_app.py

A test user is signed up in the setup function.
Closes #138

Issue #138: Fix user signup in test setup

---

app.py
requirements.txt

Issue #164: updates imports/dependencies with new monorepo modules structure

---

renovate.json

Issue #166 testing new schema to detect datastore new versions

---

app/controllers/inspections.py
app/main.py
app/models/inspections.py
app/models/label_data.py
tests/test_app.py
tests/test_inspections.py

issue #179: put inspection in fastapi

---

.github/workflows/project-issue-status.yaml

issue #216: added project issue status

---

CONTRIBUTING.md
README.md
docs/README.md
docs/otel/README.md

Added French translations to comply with language requirements.

Added French translations to README, CONTRIBUTING, Developper Documentation and Otel Documentation

---

.env.config
CONTRIBUTING.md
README.md
app/controllers/inspections.py
app/models/inspections.py
app/routes.py
docs/README.md
requirements.txt
tests/test_app.py
tests/test_inspections.py

issue #231: update datastore version to 1.0.13

---

.gitignore
app/models/label_data.py

Issue #233 : Throw an error if the registration number does not match a pattern

---

.gitignore
app/config.py
app/controllers/data_extraction.py
app/dependencies.py
app/routes.py
requirements.txt
tests/test_app.py
tests/test_data_extraction.py

This PR leverages the latest changes in the pipeline from the [dspy-experimental](https://github.com/ai-cfia/fertiscan-pipeline/tree/dspy-experimental) branch
1. Updated pipeline integration to use a unified Settings object instead of separate OCR and GPT instances
2. Removed direct dependencies on OCR and GPT classes in favor of the new pipeline Settings approach
3. Updated the data extraction controller to work with PIL Images directly
4. Added Zed editor configuration to .gitignore
5. Updated requirements.txt to use the dspy-experimental branch of fertiscan-pipeline
- Replaced individual OCR and GPT instances with a single PipelineSettings configuration object
- Modified the data extraction logic to handle image processing using PIL
- Updated test cases to reflect the new architecture …

Integrate experimental changes made to the pipeline
